CREATE TABLE `member`
(
	id VARCHAR(50) NOT NULL PRIMARY KEY,
	passwd VARCHAR(16) NOT NULL,
	name VARCHAR(10) NOT NULL,
	reg_date DATETIME NOT NULL
);

CREATE TABLE `test`
(
	num_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL,
	content TEXT NOT NULL
);